# -*- coding: utf-8 -*-
"""APIS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lbVTO5EzQmimNVmgN96RWbi6wnaijxA6
"""

import requests

def consumo_de_API(url):
    respuesta = requests.get(url)
    datos = respuesta.json()
    if respuesta.status_code == 200:
        return datos['data']
    else:
        print("Error al obtener las imágenes: ", datos)

url = "https://fakerapi.it/api/v1/images?_quantity=1&_type=kittens&_height=300"
imagenes = consumo_de_API(url)
print(imagenes)

url = "https://fakerapi.it/api/v1/books?_quantity=1"
libros = consumo_de_API(url)
print(libros)

url = "https://fakerapi.it/api/v1/persons?_quantity=1&_gender=male&_birthday_start=2005-01-01"
personas = consumo_de_API(url)
print(personas)